export const PRODUCT_TYPES = {
  // Fetch Products
  FETCH_PRODUCTS_REQUEST: "FETCH_PRODUCTS_REQUEST",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",

  // Fetch Single Product
  FETCH_PRODUCT_REQUEST: "FETCH_PRODUCT_REQUEST",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",

  // Create Product
  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",

  // Update Product
  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",

  // Delete Product
  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",

  // Search Products
  SEARCH_PRODUCTS_REQUEST: "SEARCH_PRODUCTS_REQUEST",
  SEARCH_PRODUCTS_SUCCESS: "SEARCH_PRODUCTS_SUCCESS",
  SEARCH_PRODUCTS_FAILURE: "SEARCH_PRODUCTS_FAILURE",

  // Filter Products
  FILTER_PRODUCTS_REQUEST: "FILTER_PRODUCTS_REQUEST",
  FILTER_PRODUCTS_SUCCESS: "FILTER_PRODUCTS_SUCCESS",
  FILTER_PRODUCTS_FAILURE: "FILTER_PRODUCTS_FAILURE",

  // Sort Products
  SORT_PRODUCTS_REQUEST: "SORT_PRODUCTS_REQUEST",
  SORT_PRODUCTS_SUCCESS: "SORT_PRODUCTS_SUCCESS",
  SORT_PRODUCTS_FAILURE: "SORT_PRODUCTS_FAILURE",

  // Clear Product State
  CLEAR_PRODUCT_STATE: "CLEAR_PRODUCT_STATE",
};
